### ISSUE TITLE
Versioning in branches?

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractivejs.github.io#1]
It seems that MkDocs doesn't officially support multiple versions in docs. I think we can probably sunset docs prior to 0.7, but we should probably keep edge and the previous two releases or two years of releases or something like that?

**Comment by fskreuz** [comment]
Yep. I still plan on keeping the older docs. How to do it would be a bit of a challenge, since MkDocs has a fixed set of links.

Seeing that the docs will just be plain markdown, wondering if one can just view older docs on Github while the actual site just shows the stable docs.

**Comment by fskreuz** [comment]
Or we can do it like jQuery and just accumulate the docs, adding "added on" and "deprecated on".

**Comment by evs-chris** [comment]
I think keeping non-latest versions on github will suffice. It also looks like mkdoc-pandoc might be a reasonable way to create an archive pdf/ebook/single-page html version of the docs.

Mixing versions on the same page has always seemed overly confusing to me.

**Comment by dagnelies** [comment]
There is this extension for mkdocs versionning (http://d0ugal.github.io/mkdocs-versioned/) but it's stability / suitability might be ...not ideal.

That leads me to another small question.
Let's say something changed between v0.8 and v0.9. Where should I modify the doc?
Does it also have vN.N branches? Does `dev` corresponding to "edge" and `master` to "latest"?

That information should definitely be added in the Readme.md to avoid that people modify the wrong "version".

**Comment by fskreuz** [comment]
iirc, Vue has [separate repos for older docs](https://github.com/vuejs). Wondering if we can use this scheme and if this goes well with Github org pages that treat project repos with pages as a subfolder. i.e.:

- ractive.js.org -> ractive.js.org
- 0.8 -> ractive.js.org/0.8
- 0.7 -> ractive.js.org/0.7
- and so on...

Also, I haven't gone cleaning up old docs and turning them to vanilla markdown. However, they're all available in the `legacy` directory in this repo.

**Comment by fskreuz** [comment]
closing in favor of https://github.com/ractivejs/ractivejs.github.io/issues/54
