### ISSUE TITLE
A preferred way to test components

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#111]
See https://gitter.im/ractivejs/ractive?at=59b6a3ffc101bc4e3ab2ecd8

Would be nice to document a preferred test setup, preferably one that's simple. I pointed out Ractive's own test setup which is fine and works great, but I really find writing the Karma config a bit hairy especially if you don't know all the things Karma provides.

**Comment by ceremcem** [comment]
I'm sure that someone will point a great way (this is what we call "Murphy Laws") but I think that is the simplest thing to do. Changing the language [may cleanup the code a little bit more](https://github.com/aktos-io/scada.js/blob/c04ef8d3c265df3f828fe9f55dab181549054eee/src/lib/aea/merge.ls#L70-L289) :smiley:
