### ISSUE TITLE
Need for decorator How To

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractivejs.github.io#131]
Currently there is no good start point for writing a decorator (or understanding how they work, at least) in the main page: 

### Expected: 

1. Go to https://ractive.js.org/integrations/
2. Click "Decorators"
3. There is no "How to"

**Comment by fskreuz** [comment]
That can be found here https://ractive.js.org/plugins/#decorators Same goes for the other plugins. The basic structure is provided, with comments.
