### ISSUE TITLE
Tooltip decorator example is broken 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractivejs.github.io#132]
Currently http://jondum.github.io/ractive-tooltip/demo/ is broken.

## Edit: 

Maybe this fiddle would fit the position: http://jsfiddle.net/9g3pB/108/

**Comment by fskreuz** [comment]
Closing in favor of one big list. Feel free to add to that thread. https://github.com/ractivejs/ractivejs.github.io/issues/136
