### ISSUE TITLE
Fix anchored links alignment

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#139]
Normally, anchored links will scroll to the anchor on arrival. The top menu will naturally obscure this because it's fixed to the top. Margins were added to headers so that it would bump its text below the menu (essentially adding whitespace above the header in the area where the top menu would normally cover).

But this behavior is inconsistent, and linking to an anchor would either land with the header just right in view, a bit higher, or a bit lower than where it should.

**Comment by simonlayfield** [comment]
Yip - I'm nudging things around in the docs as part of the the brand update so I can certainly take a look at this while I'm at it,

**Comment by simonlayfield** [comment]
This should be fixed as part of the rebrand merge. Not sure what the etiquette is here as far as closing issues, but it can be reviewed and closed if behaviour is as expected.

**Comment by fskreuz** [comment]
Looks like it's working. 👍
