### ISSUE TITLE
You need to fix your DNS, www.ractive.js.org doesn't resolve

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractivejs.github.io#161]
Noticed when typing in www.ractive.js.org was getting a "site can not be reached" error.

**Comment by evs-chris** [comment]
ractive,js.org is managed by js.org and forwarded here with a github cname. I don't think they support www subs for projects, or at least it doesn't look like it from their docs.

**Comment by donnyv** [comment]
Lol.... I just realized there is a "." between ractive and js. My bad.
