### ISSUE TITLE
Sidebar does not scroll when containing a lot of items

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#2]
Evident on pages that have a lot of headings:

- https://ractive.js.org/API/Initialization%20Options/
- https://ractive.js.org/API/Instance%20Methods/
- https://ractive.js.org/API/Helper%20Objects/Node%20Info/

It's a Cinder limitation, but I'd like to inform whoever is doing theming to be aware.

**Comment by fskreuz** [comment]
Fixed in https://github.com/ractivejs/ractivejs.github.io/pull/10

**Comment by p3k** [comment]
Is this a regression issue? I am currenlty not able to scroll the sidebar e.g. on https://ractive.js.org/api/

**Comment by fskreuz** [comment]
Yep, that's a bug. @evs-chris is this related to the playground changes?

**Comment by evs-chris** [comment]
Somewhat :smile:. Should be good once travis finishes deploying.
