### ISSUE TITLE
Document which operations are asynchronous and why

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#23]
Currently trying out karma-benchmark when I wondered if a method call from a template is synchronous or asynchronous. If it is synchronous, that's fine. If it is async, I have to tell Benchmark.js that it is and I should resolve the benchmark deferred in the method.

Made me wonder what other things run sync or async. Methods that return Promises are obviously async, but there might be methods that return nothing, but run async.

It would be nice to document which ones and why they do it.

**Comment by evs-chris** [comment]
Everything in ractive is sync except for the things that can't be: transitions and animate. Everything that returns a promise does so to account for transitions. The dom is still manipulated synchronously, and the promises resolve immediately if there are no transitions. Animate is the only thing that happens completely async.

**Comment by fskreuz** [comment]
Closing in favor of https://github.com/ractivejs/ractivejs.github.io/issues/64
