### ISSUE TITLE
Versionning

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractivejs.github.io#40]
Hi,

Let's say something changed between v0.8 and v0.9. Where should I modify the doc?
Does it also have vN.N branches? Is dev corresponding to "edge" and master to "latest"?

That information should definitely be added in the Readme.md to avoid that people modify the wrong "version".

**Comment by dagnelies** [comment]
It's kind of tricky ...I haven't seen something in mkdocs to do so. There is this extension (http://d0ugal.github.io/mkdocs-versioned/) but it's stability / suitability might be ...not ideal.

**Comment by fskreuz** [comment]
There's an open thread about versioning. Feel free to migrate there. :D

https://github.com/ractivejs/ractivejs.github.io/issues/1

**Comment by dagnelies** [comment]
oh, sorry about, I overlooked it.
