### ISSUE TITLE
"Edit on GitHub"

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractivejs.github.io#42]
What I'm kind of missing from the old docs is the "edit this page" link on top. This was very handy and makes it easier for people to make a change. I tried to see if it can be done with mkdocs, but it only worked with the "readthedocs" theme, not with `cinder` nor `mkdocs`.

**Comment by fskreuz** [comment]
Taking this into consideration in theme changes.

The problem with the current theme is that mkdocs expects the docs to be in the same repo as the project. Both the "Edit this page" and the Github repo link uses the same `repo_url` setting. It's currently set to the lib repo url.

**Comment by evs-chris** [comment]
There's now an edit link nestled between previous and next links at the bottom of every md page.

**Comment by dagnelies** [comment]
👍 👍 👍
