### ISSUE TITLE
Duplication in documentation for ractive.observe()

### ISSUE THREAD

**Issue by alexlibby** [ractivejs/ractivejs.github.io#59]
Whilst browsing https://ractive.js.org/concepts/data-binding/#observers, I noticed an issue with one of the statements:

_"Ractive implements pub/sub with ractive.on(), ractive.off() and ractive.fire(), ractive.off() and ractive.fire - see Events for more info."_

It's a minor issue, but unless I'm mistaken, it looks like part of the sentence has been duplicated? I think it should read _"Ractive implements pub/sub with ractive.on(), ractive.off() and ractive.fire() - see Events for more info."_...

**Comment by fskreuz** [comment]
Yup, spotted that the other day. Probably the result of a mighty find-and-replace. 😁 

Thanks for the report. 👍

**Comment by alexlibby** [comment]
Yeah - I suspected as much! If I find any more of these, would it help if I reported them here for you?

**Comment by fskreuz** [comment]
That would be great! Don't stress yourself over it though. 😄

**Comment by fskreuz** [comment]
Page already revised. Duplication is now gone. 😄
