### ISSUE TITLE
Document missing stuff

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#64]
A laundry-list of missing apis and configs

- [x] `ondestruct`
- [x] `ractive.once`
- [x] Args placeholders (see https://github.com/ractivejs/ractivejs.github.io/issues/64#issuecomment-308201304)
- [x] Server-side rendering
- [x] Migrations up to 0.7
- [x] Ractive's CLI (at least an overview)
- [x] `arguments` available on `on-*` expressions.
- [x] Anchors (`<# ... >`)
- [x] Which parts of Ractive are sync and async
- [x] Document the existence of the regular build, the runtime build and the ES6 build.
- [x] Interpolators (see: https://gitter.im/ractivejs/ractive?at=59720f084bcd78af56d165d7)
- [x] CSP
- [x] The `allowExpressions` init option.
- [x] `ractive.link()`'s third argument.
- [x] `ractive.resetTemplate()` https://github.com/ractivejs/docs.ractivejs.org/issues/188
- [x] `Ractive.parse()` missing options?
- [x] Context object properties and methods (some appear to be missing?)
- [ ] Backticks argument syntax for transitions and decorators (and maybe more) https://github.com/ractivejs/ractive/issues/3028
- [ ] Progressive enhancement
- [x] The recently exposed static methods (findPlugin and friends) 
- [x] Document why `css` is component-only at the moment.
- [x] Examples. Examples everywhere!

**Comment by sabob** [comment]
Not sure if already available, but if not can we also document component events? I recall one can do things like:

<mycomp on-custom-event="@.myMethod($1, $2)">

And mycomp can fire that event like so:

this.fire( "custom-event", arg1, arg2 );

**Comment by fskreuz** [comment]
I think that's covered here https://ractive.js.org/concepts/event-management/. API details are on https://ractive.js.org/api/instance-methods/#ractivefire. This used to be in Extend/Components but the concept encompasses more than just component events.

**Comment by sabob** [comment]
Sorry I forgot a quote in my comment above. Updated below:

```<mycomp on-custom-event="@.myMethod($1, $2)">```

```this.fire( "comp-event", arg1, arg2 );```

I'm after documentation for argument placeholders, $1, $2.

Would also be nice if [https://ractive.js.org/extend/components/](https://ractive.js.org/extend/components/) discussed how to communicate with components eg.

* we pass data to components through mappings ```<comp person="{{person}}">```
* components talk to parents through firing events: ```<comp on-click="@.fire('comp-event', someData)">```

**Comment by fskreuz** [comment]
Mappings is over at data management https://ractive.js.org/concepts/data-management/#mappings

Oh, the args. Forgot that those exist. 👍

**Comment by fskreuz** [comment]
Args references documented in https://ractive.js.org/api/references/#n

**Comment by sabob** [comment]
I think having all component related info on the same page is more user friendly. Especially new users. Otherwise one has to read all the documentation before getting a clear picture.

Useful topics to cover for components:

* data flow
  - data is passed from parent to child through mappings,
  - data flows up from components to parents through events
This paradigm maximizes reusability in that child doesn't know about parent

* managed vs unmanaged
  - managed components is registered with a Ractive instance and instantiated by Ractive
  - unmanaged components can be instantiated manually and attached to a parent through attachChild and anchor.

If you agree I can do a PR for this change at some stage.

**Comment by fskreuz** [comment]
Those things used to be in Extend/Components. But when I cleaned up the data and events pages, there was much duplication. Mappings are just another step in resolution, and events aren't specific to components. So I just moved them out to the concepts pages.

Where your suggestions may end up with is on a "Workflows" page since it's not the only way to do it. You can have the usual two-way binding, or flux, or your mapping+events (which sounds very much like Angular2). Would be nice to have a page showcase the different ways to use Ractive.

**Comment by sabob** [comment]
There are indeed different ways to do data flow. I was aiming for a default (recommended) approach. Otherwise newbies like myself can go down a path when we don't fully understand the trade offs.

**Comment by fskreuz** [comment]
Yup, agreed. Feel free to do a PR whenever ready. 🚢
