### ISSUE TITLE
home page tweaks

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractivejs.github.io#81]
Since home pages are the most important one for a lib, we might want to consider:

* move the "rainbow chat/stat bar"in the middle of the page to the footer, or somewhere else?
* replace "About Ractive" with a "Why Ractive".

Why Ractive could mention that Ractive is a true template engine based on Mustache, and show a snippet comparing a Mustache template vs a "custom attribute" based one. To me this is the main selling point of Ractive and new users should be able to see if this is to their liking or not.

I don't know the landscape well enough to know what other "unique" features Ractive provides. Perhaps it is more dynamic? Dynamic components for example?

**Comment by evs-chris** [comment]
I was trying to keep the current version and a link to chat fairly prominent on the home page, though it could certainly be something other than the rainbow of badges. Ideally, in a month or four, all of them but the twitter badge will be green most of the time 😄.

When the playground gets nice and embeddable, I'd like to punt the about section down a bit and replace it with an inline live demo - kinda like the old site but more in-depth.

**Comment by fskreuz** [comment]
> move the "rainbow chat/stat bar"in the middle of the page to the footer, or somewhere else?

There's a bit of history to this one. It used to be on the top of the page. Then was moved to the footer. I removed it because it seem to have caused page loading issues on iOS. Then it's now in the middle. 😄

**Comment by fskreuz** [comment]
I think we can close this. Playground is on site, and demos can invoke it.
