### ISSUE TITLE
temperatures.json loaded from wrong location in tutorials

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#87]
Due to the merge of pages, the [Animation tutorial ](https://ractive.js.org/tutorials/animation/) is broken since it loads `temperatures.json` from the old location. Playground code needs updating.

**Comment by Inversion-des** [comment]
Seems there is some problem again:
`xhr.open( 'GET', '/get-started/tutorials/temperatures.json' );` — 404
for me it works with `/tutorials/temperatures.json `
