### ISSUE TITLE
Example for demonstrating communication between components 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractivejs.github.io#89]
I prepared a reproduction code for a possible bug (an undocumented breaking change) in between 0.9.2 and 0.9.3 and guess what: I found nothing :D 

Maybe [that code](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT4gCGeBgRo0XGgxoAzdgDsAxigqtVACgC2GPMoCUwGhjQoAKhX1oOKXUuOGTNHE1VeASkk3UaAB06qz6XDpoqigYANoA5AisAObJaDDxALoKNH4BVMFoAB7oqmS6wF5MKOjhyOiQNAAGVSjVJGAATHwAMilpMDSGyY3AwMM4OEJdfK3VTXitZKhIo3Mow40sZGhKSOwIKEOYGEhpLK34rToUqhQojSoaWjq6ZusoYBQYQa+V3m1AZYUABZE5nNCPNQBHQ0XRoKiucFpYzqJAIBAAI38AGt3P9qoTAZ9vkFgbp4sN4kiMKc0iYANzrInSWRcXQARgADDzjE8YXp3gCiUS0RjseocW9mYCcEFMbdyiSMCYTDLPMKUDg1QCNdqqqo8loCiEwhFVFEYgl9ABPAC0oXCkWiWRyRsCQWKpXKBJqaDqqEhzXWJC4fBBNpojvNlosKFQ7Awo2AWATGEmQjD6wW1zudweymhL0FvuqoVUGFYMiCSWSFNtDrNzqO3zo+Yo6IoAC80GQgvFGetawMcsqgjBWKwUEElIqAMJNi3RCnD9ID9asuScnlcvlF7QlmWrmBkqz1jDJak0eJgNA2+8Dpma6qb9nc3mF54Ht6lwHVYY5Cwt4YqwNCfOkaAAIQXM+gLHjOFAwGgFLAmCtIQlewx7l+rxCiKf41F8PzkvEqYoImV4sLaxzoWkcLxCwNAANRDBezE0CwA50BgNBIeoaCBGQNCYpGx40ByFhoOWQlnKwLA6vh1RygqZS6MqqpPvhymKmpRGqus2mqepClal4+qqBaADuuT+MayG+mgCCNPEADEjg8Cg1KtLUXD1EGLSaiQx4CIIwUhg20bNiFEWLpasyagF2q4EAA) could be used in the examples section to show how to communicate between components.

**Comment by fskreuz** [comment]
That suggestion can probably be included in https://github.com/ractivejs/ractivejs.github.io/pull/73 . 😄

**Comment by fskreuz** [comment]
Also, as much as I like writing docs, I'm not knowledgeable about the breaking change between 0.9.2 and 0.9.3. 😬 

Feel free to post a PR to update the migration section tho. PRs are always welcome.

**Comment by evs-chris** [comment]
The breaking change was probably a bug fix from ractivejs/ractive#3033, namely that firing with an object first arg will extend the context rather than passing an object first arg. If you need to fire an object first arg, you have to throw an empty object in there first e.g. `this.fire('someEvent', {}, { first: true })`. Polymorhpic functions in js are unpleasant :(

**Comment by fskreuz** [comment]
> Polymorhpic functions in js are unpleasant

![image](https://user-images.githubusercontent.com/1582932/28730911-caf34a78-739f-11e7-9162-ad98ef99968a.png)

**Comment by fskreuz** [comment]
Closing in favor of https://github.com/ractivejs/ractivejs.github.io/issues/74
