### ISSUE TITLE
Update event handler examples to use "context" and not event

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#93]
From https://stackoverflow.com/questions/45666108/upgrading-from-0-7-to-0-9-how-do-i-access-my-events-keypath/45674285?noredirect=1#comment78322230_45674285

**Comment by JonDum** [comment]
I found two as of c72a0ab

```
concepts.md
891:    this.on('ancestorbuttonclick', event => {
894:    this.on('descendantbuttonclick', event => {

api.md
875:    this.on('clickedproxy', event => {
```

**Comment by fskreuz** [comment]
Fixed what I could find in https://github.com/ractivejs/ractivejs.github.io/commit/f889a82d4545647bf46ec38aa9a418f99132a5d3
