### ISSUE TITLE
Why is single backslash used everywhere in the documentation instead of double backslash?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractivejs.github.io#96]
Ractive uses a single backslash (`\`) as the escape character in the strings but if we want to include a single backslash in the string, we should use double backslash (`\\`). 

Why does documentation contain single backslash strings in the examples?

For example, in [Ractive.splitKeyPath()](https://github.com/ractivejs/ractivejs.github.io/blob/a357305f879cbc0abbaabf84af61d54567cfd570/docs/api.md#ractivesplitkeypath) section, we have the following example: 

```js
Ractive.splitKeypath( 'foo.bar\.baz' ); // [ 'foo', 'bar.baz' ]
```

But this does not produce `['foo', 'bar.baz']`: [playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gB4AEAvEQEoCGAxgC4CWAbggHS4AOANvbQNIIBPdpVpgAFEQDkAMwD2slgCNKMADqqllAF6SiASgDcqgHbVZx3LM6tOslGIJ6TmIA)

Correct form should be [`Ractive.splitKeypath( 'foo.bar\\.baz' )`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gB4AEAvEQEoCGAxgC4CWAbggHS4AOANvbQNIIBPdpVpgAFEQDkAMwD2slgCNKMADrrVSygC9JRAJQBuVQDtqsk7lmdWnWSjEF9pzEA), or am I missing something?

**Comment by fskreuz** [comment]
I'm also no expert in this area, since I generally avoid invalid characters on my keys or can never have them at all and never had to escape keys. You might want to check the unit tests tho, it might give hints.

**Comment by MartinKolarik** [comment]
@ceremcem is right here. You need two backslashes because one's eaten by JS.

**Comment by fskreuz** [comment]
> one's eaten by JS
👻
